#-------------------------------
#-------------------------------
# Site Settings

title: WELCOME #Avenco
logo: # You can add own logo. For example '/images/logo.png'.
description: Avenco – Creative Portfolio Theme for Jekyll

# menu__settings:
#   menu__items:
#     - title: 'Home'
#       url: '/'
#     - title: 'Projects'
#       url: '/projects/'
#     - title: 'Blog'
#       url: '/blog/'
#     - title: 'Pages'
#       submenu:
#       - url: '/about'
#         title: 'About'
#       - url: '/elements'
#         title: 'Elements'

menu__settings:
  menu__items:
  
    - title: 'Home'
      url: '/'
    
    - title: 'Projects'
      url: '/projects/'
    
    - title: 'Blog'
      url: '/blog/'
    
    - title: 'About'
      url: '/about/'
      
    - title: 'Pages'
      submenu:
      - url: '/about'
        title: 'About'
      - url: '/elements'
        title: 'Elements'

# Call to action button
cta__button__text: Get in touch

# Add global cover image (This field adds a background to the top and bottom of the site.)
cover__image: '/images/37.jpg'


#-------------------------------
#-------------------------------
# Author Settings

author:
  name: Frank Sierra
  title: Hi! I’m Frank Sierra
  bio: ML Engineer based in Ireland, currently bringing the AI torch to the field of Veterinary Parasitology.  When I’m not working, I’m probably playing tennis, climbing or traveling somewhere.
  #image: '/images/01.jpg'
  #avatar: '/images/avatar.jpg'
  image: '/images/me.jpg'
  avatar: '/images/me.jpg'
  button__text: See my projects


#-------------------------------
#-------------------------------
# Projects Settings

projects__settings:
  projects__title: Latest <span class="text-span">Projects</span> # Add a 'text-span' class to highlight text.
  projects__description: Here are some of my latest projects! They range from deep learning to cognitive neuroscience and veterinary epidemiology.


#-------------------------------
#-------------------------------
# Testimonials Section

testimonial__title: People I've  <span class="text-span">Worked</span> With # Add a 'text-span' class to highlight text.

testimonial-items:
  - name: "Vineeth Das"
    image: "/images/client-01-vineeth.jpeg"
    designation : "Associate Director"
    content : "Frank and I worked closely together in the data science team, where he brought sharp analytical thinking and a strong command of modeling techniques to every project. From building predictive models and refining code to troubleshooting complex problems and optimizing performance, Frank was involved in every step of the process. His collaborative approach and attention to detail made him a key contributor and a pleasure to work with."

  - name: "Ilkay Isik"
    image: "/images/client-02-ilkay.jpg"
    designation : "Data & Technology Consultant"
    content : "Quamquam id quidem, infinitum est in hac urbe, Ita multo sanguine profuso in laetitia et in victoria est mortuus. Atqui pugnantibus et contrariis consiliisque."

  - name: "Giovanni Di Liberto"
    image: "/images/client-03-giovanni.jpg"
    designation : "Professor"
    content : "Quamquam id quidem, infinitum est in hac urbe, Ita multo sanguine profuso in laetitia et in victoria est mortuus. Atqui pugnantibus et contrariis consiliisque."

  - name: "Pol van Rijn"
    image: "/images/client-04-pol.jpg"
    designation : "Researcher"
    content : "Quamquam id quidem, infinitum est in hac urbe, Ita multo sanguine profuso in laetitia et in victoria est mortuus. Atqui pugnantibus et contrariis consiliisque."


#-------------------------------
#-------------------------------
# Blog Section

blog__settings:
  blog__title: Recent <span class="text-span">Blog</span> Posts # Add a 'text-span' class to highlight text.
  blog__description:

#-------------------------------
#-------------------------------
# Contact Settings

contact__settings:
  contact__email: franklenin.sierra@gmail.com # Add your email for contact form
  contact__title: <span class="text-span">Get</span> in touch # Add a title to your form
  contact__description: Avenco comes with a built-in contact form. # Add a description to your form

# NOTE
# Avenco comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.

#-------------------------------
#-------------------------------
# Newsletter Settings
mailchimp__settings:
  mailchimp__title: <span class="text-span">Join</span> my mailing list # Add your title
  mailchimp__text: " 'Get inspiration, updates and', 'cool stuff about design!' " # Add descriptions to the form by wrapping the text in single quotes. If you want to use more than one sentence, be sure to separate them with a comma.
  mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
  mailchimp__button__text: Subscribe # Add your button text

#-------------------------------
#-------------------------------
# Comment Section (Disqus)
disqus-identifier: anvodstudio-demo # add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
#-------------------------------
# Footer Settings
# Social Links
# Example of adding a new link to the footer - {icon: "ion-logo-facebook", link: "https://facebook.com"}
# Other icons can be found at https://ionicons.com/v4/
social:
- {icon: "ion-logo-google", link: "https://scholar.google.com/citations?user=EYx6UuIAAAAJ&hl"} # If you want to use a generic Google icon
- {icon: "ion-logo-linkedin", link: "https://www.linkedin.com/in/franklenin/"}
- {icon: "ion-logo-github", link: "https://github.com/franklenin"}
- {icon: "ion-logo-twitter", link: "https://x.com/frankc_sierra"}  #link: "https://twitter.com"
#- {icon: "ion-logo-pinterest", link: "https://pinterest.com"}
#- {icon: "ion-logo-codepen", link: "https://codepen.io"}
#- {icon: "ion-logo-vimeo", link: "https://vimeo.com"}
#- {icon: "ion-logo-youtube", link: "https://youtube.com"}
